version: '3'

networks:
  dev:
    driver: bridge

services:
  book_shop:
    image: docker.io/library/bookshop:v1.1
    depends_on:
      - "app_db"
    container_name: book_shop_services
    ports:
      - "8000:80"
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Server=app_db;Port=5432;Database=${POSTGRES_DB};IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
        - dev
  app_db:
    image: "postgres:16.1"
    container_name: app_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
        - "5433:5432"
    restart: always
    networks:
        - dev
