name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./BookShopMVC
        file: ./BookShopMVC/Dockerfile
        push: true
        tags: artan-hasani/devops-project23/bookshop:latest

    - name: Set up Docker Compose
      run: |
        sudo docker-compose -f ./BookShopMVC/docker-compose.yml build
        sudo docker-compose -f ./BookShopMVC/docker-compose.yml up -d

    - name: Stop Docker Compose
      run: sudo docker-compose -f ./BookShopMVC/docker-compose.yml down
